apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: storefront-web
  description: Next.js storefront frontend, consumes storefront-api.
  annotations:
    github.com/project-slug: thlai15/storefront-web
  tags:
    - nextjs
    - typescript
spec:
  type: website
  lifecycle: experimental
  owner: group:frontend-team
  system: storefront
  consumesApis:
    - storefront-api
