apiVersion: apps/v1
kind: Deployment
metadata:
  name: storefront-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: storefront-web
  template:
    metadata:
      labels:
        app: storefront-web
    spec:
      containers:
        - name: storefront-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
